function METI_DTTH_PNT_BusInfo ()

% Generated by make_Xlsx2BusObj : METI_DTTH_PNT_BusInfo 
% PHI_TM_RD 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'PHI_Oil_TM_RD';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

% PHI_TM_RD バスの定義
PHI_TM_RD = Simulink.Bus;
PHI_TM_RD.HeaderFile = '';
PHI_TM_RD.Description = sprintf ('');
PHI_TM_RD.DataScope = 'Auto';
PHI_TM_RD.Alignment = -1;
PHI_TM_RD.Elements = elems;
clear elems;
assignin('base', 'PHI_TM_RD',PHI_TM_RD);
%---------------------%

% TMTH_Info 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'T_TMTH_PNT_CVTF_K';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'T_DFBlock_K';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

elems(3) = Simulink.BusElement;
elems(3).Name = 'R_CVTF_warmer_tgt_KpW';
elems(3).Dimensions = 1;
elems(3).DimensionsMode = 'Fixed';
elems(3).DataType = 'double';
elems(3).SampleTime = -1;
elems(3).Complexity = 'real';
elems(3).SamplingMode = 'Sample based';
elems(3).Min = [];
elems(3).Max = [];
elems(3).DocUnits = '';
elems(3).Description = sprintf (''); 

% TMTH_Info バスの定義
TMTH_Info = Simulink.Bus;
TMTH_Info.HeaderFile = '';
TMTH_Info.Description = sprintf ('');
TMTH_Info.DataScope = 'Auto';
TMTH_Info.Alignment = -1;
TMTH_Info.Elements = elems;
clear elems;
assignin('base', 'TMTH_Info',TMTH_Info);
%---------------------%

% PHI_TM_ATM 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'PHI_DFTH_PNT_W';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'PHI_TMTH_PNT_W';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

% PHI_TM_ATM バスの定義
PHI_TM_ATM = Simulink.Bus;
PHI_TM_ATM.HeaderFile = '';
PHI_TM_ATM.Description = sprintf ('');
PHI_TM_ATM.DataScope = 'Auto';
PHI_TM_ATM.Alignment = -1;
PHI_TM_ATM.Elements = elems;
clear elems;
assignin('base', 'PHI_TM_ATM',PHI_TM_ATM);
%---------------------%

% PHI_TM_ENG 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'PHI_TM_CVTF_Resi_W';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'PHI_ENGBlock_Resi2_W';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

% PHI_TM_ENG バスの定義
PHI_TM_ENG = Simulink.Bus;
PHI_TM_ENG.HeaderFile = '';
PHI_TM_ENG.Description = sprintf ('');
PHI_TM_ENG.DataScope = 'Auto';
PHI_TM_ENG.Alignment = -1;
PHI_TM_ENG.Elements = elems;
clear elems;
assignin('base', 'PHI_TM_ENG',PHI_TM_ENG);
%---------------------%

% T_TMTH_PNT 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'T_TMTH_PNT_CVTF_K';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'T_DFBlock_K';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

% T_TMTH_PNT バスの定義
T_TMTH_PNT = Simulink.Bus;
T_TMTH_PNT.HeaderFile = '';
T_TMTH_PNT.Description = sprintf ('');
T_TMTH_PNT.DataScope = 'Auto';
T_TMTH_PNT.Alignment = -1;
T_TMTH_PNT.Elements = elems;
clear elems;
assignin('base', 'T_TMTH_PNT',T_TMTH_PNT);
%---------------------%

% T_ENG_TM 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'T_ENGTH_PNT_Coolant_K';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'T_ENG_Block_K';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

% T_ENG_TM バスの定義
T_ENG_TM = Simulink.Bus;
T_ENG_TM.HeaderFile = '';
T_ENG_TM.Description = sprintf ('');
T_ENG_TM.DataScope = 'Auto';
T_ENG_TM.Alignment = -1;
T_ENG_TM.Elements = elems;
clear elems;
assignin('base', 'T_ENG_TM',T_ENG_TM);
%---------------------%

% T_RD_TM 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'T_PT_TH_K';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

% T_RD_TM バスの定義
T_RD_TM = Simulink.Bus;
T_RD_TM.HeaderFile = '';
T_RD_TM.Description = sprintf ('');
T_RD_TM.DataScope = 'Auto';
T_RD_TM.Alignment = -1;
T_RD_TM.Elements = elems;
clear elems;
assignin('base', 'T_RD_TM',T_RD_TM);
%---------------------%

% T_ATM_TM 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'T_ATM_PNT_TM_K';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'T_ATM_PNT_DF_K';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

% T_ATM_TM バスの定義
T_ATM_TM = Simulink.Bus;
T_ATM_TM.HeaderFile = '';
T_ATM_TM.Description = sprintf ('');
T_ATM_TM.DataScope = 'Auto';
T_ATM_TM.Alignment = -1;
T_ATM_TM.Elements = elems;
clear elems;
assignin('base', 'T_ATM_TM',T_ATM_TM);
%---------------------%

