function METI_TM_CNT_BusInfo ()

% Generated by make_Xlsx2BusObj : METI_TM_CNT_BusInfo 
% TM_CNT_out 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'flag_Lockup';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'omg_Slip_rpm';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

elems(3) = Simulink.BusElement;
elems(3).Name = 'ratio_CVT';
elems(3).Dimensions = 1;
elems(3).DimensionsMode = 'Fixed';
elems(3).DataType = 'double';
elems(3).SampleTime = -1;
elems(3).Complexity = 'real';
elems(3).SamplingMode = 'Sample based';
elems(3).Min = [];
elems(3).Max = [];
elems(3).DocUnits = '';
elems(3).Description = sprintf (''); 

elems(4) = Simulink.BusElement;
elems(4).Name = 'R_CVTF_warmer_tgt_KpW';
elems(4).Dimensions = 1;
elems(4).DimensionsMode = 'Fixed';
elems(4).DataType = 'double';
elems(4).SampleTime = -1;
elems(4).Complexity = 'real';
elems(4).SamplingMode = 'Sample based';
elems(4).Min = [];
elems(4).Max = [];
elems(4).DocUnits = '';
elems(4).Description = sprintf (''); 

% TM_CNT_out バスの定義
TM_CNT_out = Simulink.Bus;
TM_CNT_out.HeaderFile = '';
TM_CNT_out.Description = sprintf ('');
TM_CNT_out.DataScope = 'Auto';
TM_CNT_out.Alignment = -1;
TM_CNT_out.Elements = elems;
clear elems;
assignin('base', 'TM_CNT_out',TM_CNT_out);
%---------------------%

% TM_CNT_CAN_Tx 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'flag_Lockup';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'omg_Slip_rpm';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

% TM_CNT_CAN_Tx バスの定義
TM_CNT_CAN_Tx = Simulink.Bus;
TM_CNT_CAN_Tx.HeaderFile = '';
TM_CNT_CAN_Tx.Description = sprintf ('');
TM_CNT_CAN_Tx.DataScope = 'Auto';
TM_CNT_CAN_Tx.Alignment = -1;
TM_CNT_CAN_Tx.Elements = elems;
clear elems;
assignin('base', 'TM_CNT_CAN_Tx',TM_CNT_CAN_Tx);
%---------------------%

% TM_CNT_Info 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'tScope_Luckup';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'tScope_CVTratio';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

% TM_CNT_Info バスの定義
TM_CNT_Info = Simulink.Bus;
TM_CNT_Info.HeaderFile = '';
TM_CNT_Info.Description = sprintf ('');
TM_CNT_Info.DataScope = 'Auto';
TM_CNT_Info.Alignment = -1;
TM_CNT_Info.Elements = elems;
clear elems;
assignin('base', 'TM_CNT_Info',TM_CNT_Info);
%---------------------%

% TM_CNT_CAN_Rx 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'open_throttle_per';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'T_ENGTH_PNT_Coolant_degC';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

elems(3) = Simulink.BusElement;
elems(3).Name = 'IdleSpeed_Target';
elems(3).Dimensions = 1;
elems(3).DimensionsMode = 'Fixed';
elems(3).DataType = 'double';
elems(3).SampleTime = -1;
elems(3).Complexity = 'real';
elems(3).SamplingMode = 'Sample based';
elems(3).Min = [];
elems(3).Max = [];
elems(3).DocUnits = '';
elems(3).Description = sprintf (''); 

elems(4) = Simulink.BusElement;
elems(4).Name = 'v_VL_PNT_kmph';
elems(4).Dimensions = 1;
elems(4).DimensionsMode = 'Fixed';
elems(4).DataType = 'double';
elems(4).SampleTime = -1;
elems(4).Complexity = 'real';
elems(4).SamplingMode = 'Sample based';
elems(4).Min = [];
elems(4).Max = [];
elems(4).DocUnits = '';
elems(4).Description = sprintf (''); 

elems(5) = Simulink.BusElement;
elems(5).Name = 'trq_BK_PNT_Nm';
elems(5).Dimensions = 1;
elems(5).DimensionsMode = 'Fixed';
elems(5).DataType = 'double';
elems(5).SampleTime = -1;
elems(5).Complexity = 'real';
elems(5).SamplingMode = 'Sample based';
elems(5).Min = [];
elems(5).Max = [];
elems(5).DocUnits = '';
elems(5).Description = sprintf (''); 

% TM_CNT_CAN_Rx バスの定義
TM_CNT_CAN_Rx = Simulink.Bus;
TM_CNT_CAN_Rx.HeaderFile = '';
TM_CNT_CAN_Rx.Description = sprintf ('');
TM_CNT_CAN_Rx.DataScope = 'Auto';
TM_CNT_CAN_Rx.Alignment = -1;
TM_CNT_CAN_Rx.Elements = elems;
clear elems;
assignin('base', 'TM_CNT_CAN_Rx',TM_CNT_CAN_Rx);
%---------------------%

