function METI_TM_PNT_BusInfo ()

% Generated by make_Xlsx2BusObj : METI_TM_PNT_BusInfo 
% TM_PNT_Info 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'tScope_CVTLoss';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'trq_Flywheel2';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

elems(3) = Simulink.BusElement;
elems(3).Name = 'w_Torque_Converter2';
elems(3).Dimensions = 1;
elems(3).DimensionsMode = 'Fixed';
elems(3).DataType = 'double';
elems(3).SampleTime = -1;
elems(3).Complexity = 'real';
elems(3).SamplingMode = 'Sample based';
elems(3).Min = [];
elems(3).Max = [];
elems(3).DocUnits = '';
elems(3).Description = sprintf (''); 

elems(4) = Simulink.BusElement;
elems(4).Name = 'w_Variator_radps';
elems(4).Dimensions = 1;
elems(4).DimensionsMode = 'Fixed';
elems(4).DataType = 'double';
elems(4).SampleTime = -1;
elems(4).Complexity = 'real';
elems(4).SamplingMode = 'Sample based';
elems(4).Min = [];
elems(4).Max = [];
elems(4).DocUnits = '';
elems(4).Description = sprintf (''); 

elems(5) = Simulink.BusElement;
elems(5).Name = 'trq_Torque_Converter2';
elems(5).Dimensions = 1;
elems(5).DimensionsMode = 'Fixed';
elems(5).DataType = 'double';
elems(5).SampleTime = -1;
elems(5).Complexity = 'real';
elems(5).SamplingMode = 'Sample based';
elems(5).Min = [];
elems(5).Max = [];
elems(5).DocUnits = '';
elems(5).Description = sprintf (''); 

elems(6) = Simulink.BusElement;
elems(6).Name = 'trq_Variator_Nm';
elems(6).Dimensions = 1;
elems(6).DimensionsMode = 'Fixed';
elems(6).DataType = 'double';
elems(6).SampleTime = -1;
elems(6).Complexity = 'real';
elems(6).SamplingMode = 'Sample based';
elems(6).Min = [];
elems(6).Max = [];
elems(6).DocUnits = '';
elems(6).Description = sprintf (''); 

% TM_PNT_Info バスの定義
TM_PNT_Info = Simulink.Bus;
TM_PNT_Info.HeaderFile = '';
TM_PNT_Info.Description = sprintf ('');
TM_PNT_Info.DataScope = 'Auto';
TM_PNT_Info.Alignment = -1;
TM_PNT_Info.Elements = elems;
clear elems;
assignin('base', 'TM_PNT_Info',TM_PNT_Info);
%---------------------%

% PHI_TM_PNT 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'W_TM_PNT_W';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'Q_Tire_rol_resi';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

% PHI_TM_PNT バスの定義
PHI_TM_PNT = Simulink.Bus;
PHI_TM_PNT.HeaderFile = '';
PHI_TM_PNT.Description = sprintf ('');
PHI_TM_PNT.DataScope = 'Auto';
PHI_TM_PNT.Alignment = -1;
PHI_TM_PNT.Elements = elems;
clear elems;
assignin('base', 'PHI_TM_PNT',PHI_TM_PNT);
%---------------------%

% sensor_TM_PNT 要素の定義
clear elems;
elems(1) = Simulink.BusElement;
elems(1).Name = 'n_TM_PNT_rpm';
elems(1).Dimensions = 1;
elems(1).DimensionsMode = 'Fixed';
elems(1).DataType = 'double';
elems(1).SampleTime = -1;
elems(1).Complexity = 'real';
elems(1).SamplingMode = 'Sample based';
elems(1).Min = [];
elems(1).Max = [];
elems(1).DocUnits = '';
elems(1).Description = sprintf (''); 

elems(2) = Simulink.BusElement;
elems(2).Name = 'T_TMTH_PNT_CVTF_degC';
elems(2).Dimensions = 1;
elems(2).DimensionsMode = 'Fixed';
elems(2).DataType = 'double';
elems(2).SampleTime = -1;
elems(2).Complexity = 'real';
elems(2).SamplingMode = 'Sample based';
elems(2).Min = [];
elems(2).Max = [];
elems(2).DocUnits = '';
elems(2).Description = sprintf (''); 

% sensor_TM_PNT バスの定義
sensor_TM_PNT = Simulink.Bus;
sensor_TM_PNT.HeaderFile = '';
sensor_TM_PNT.Description = sprintf ('');
sensor_TM_PNT.DataScope = 'Auto';
sensor_TM_PNT.Alignment = -1;
sensor_TM_PNT.Elements = elems;
clear elems;
assignin('base', 'sensor_TM_PNT',sensor_TM_PNT);
%---------------------%

