TRUE  =  1;       	%論理的「真」定義
FALSE =  0 ;      	%論理的「偽」定義
LoopTime=	10.0;	%制御周期
MaxGr	=	12;		%最大ギヤ段数 (Neutral,Rev含む)
MaxCL	=	11;		%最大クラッチ数
MaxSyn	=	10;		%最大シンクロ数
GrRev	=	11;		%everseGearの配列番号
GrNP 	=	0;		%eutralの配列番号
Shift_Up=	1 ;
Shift_CD= 	2 ;
Shift_TD= 	3 ;
Shift_ND=	4 ;
Shift_NR=	5 ;
PI = 3.141592  ;
